apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-hook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  source:
    repoURL: https://github.com/linhdo04/argocd-learning.git
    targetRevision: main
    path: labs/hooks
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-hook
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - FailOnSharedResource=true
