apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-web-content
  labels:
    app.kubernetes.io/name: demo-web
    app.kubernetes.io/part-of: argocd-learning
data:
  index.html: |
    <!doctype html>
    <html lang="vi">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Argo CD Lab</title>
      </head>
      <body>
        <h1>Xin chào từ Argo CD!!!!!!!!</h1>
        <p>Ứng dụng này đang được quản lý bằng GitOps.</p>
      </body>
